### ISSUE TITLE
Homepage's link to OWASP CRS is broken

### ISSUE THREAD

**Issue by robertlagrant** [corazawaf/coraza.io#180]
## Description

Homepage's link to OWASP CRS is broken.

### Steps to reproduce

Go to the homepage and hover the link.

### Expected result

It should say https://coraza.io/docs/tutorials/coreruleset/

### Actual result

It says https://coraza.io/#

**Comment by M4tteoP** [comment]
Fixed by https://github.com/corazawaf/coraza.io/pull/181, thanks!
