### ISSUE TITLE
execution-flow/#phases image description is incorrect

### ISSUE THREAD

**Issue by WesleyOne** [corazawaf/coraza.io#209]
## Description

Describe the issue that you're seeing.

https://coraza.io/docs/seclang/execution-flow/#phases

 image description is incorrect

<img width="1236" alt="err_coraza_io_docs_seclang_execution-flow#phases" src="https://github.com/corazawaf/coraza.io/assets/24919538/59652742-e1eb-461f-95ed-e8e60fb8e571">

### Steps to reproduce

Clear steps describing how to reproduce the issue. Please please please link to a demo project if possible, this makes your issue _much_ easier to diagnose (seriously).

### Expected result

Add Response Headers

### Actual result

Add Request Headers

### Environment

https://coraza.io/docs/seclang/execution-flow/#phases

**Comment by jcchavezs** [comment]
I think @jptosso had the right graphic somewhere.

**Comment by jptosso** [comment]
Yup
![Untitled Workspace (8)](https://github.com/corazawaf/coraza.io/assets/1236942/eebfc612-2d4d-4df9-b7cb-1e61ac9dd8be)
